Bot Token Variable Name: SpeedyBotToken 

Prefix: ":"

Playing Status: "{prefix}The Devil is a female{prefix}"

Log channel ID: 733481879381999646

Embed Settings:
  Color: 
    r: 255
    g: 53
    b: 53
  
  Footer: 
    Text: Suck pp
    Icon URL: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e1b4531d-9638-4e16-bab2-8982c104bdba/dcv0rk1-645f1918-f50d-4474-89d3-242a3c4b7f22.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvZTFiNDUzMWQtOTYzOC00ZTE2LWJhYjItODk4MmMxMDRiZGJhXC9kY3YwcmsxLTY0NWYxOTE4LWY1MGQtNDQ3NC04OWQzLTI0MmEzYzRiN2YyMi5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.cWjM2jxF6adZW_xL5-sIghwr1o-8KkWTA9KVl0G9tkQ


